### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by divyat09** [Genentech/nodags-flows#1]
I am facing this issue while trying to get the data generation to work. This happens from the models/functions.py file while importing the library turtle.

```
    from turtle import forward
  File "/usr/lib/python3.10/turtle.py", line 107, in <module>
    import tkinter as TK
ModuleNotFoundError: No module named 'tkinter'
```

Could you please share some requirement file so that I have access to the correct dependencies that you have used for the experiments. Thanks!

**Comment by muralikgs** [comment]
Hi, Thanks for pointing out the issue. The first imports in the function file aren't used in the rest of the code.

```python
from cmath import e
from turtle import forward
```
You can comment on these lines and you should be fine with using it. I will also update the code base with the lines removed. 

```python
#from cmath import e
#from turtle import forward
```
The major requirements are listed in the README file. Let me know if you're still facing any issues after this. 

EDIT: The first two lines are removed from the code.
